import { useEffect } from 'react';
import {
  isRouteErrorResponse,
  Links,
  Meta,
  Outlet,
  Scripts,
  ScrollRestoration,
} from 'react-router';

import type { Route } from './+types/root';
import { useSessionBootstrap } from './stores/use-session';
import './app.css';

export const links: Route.LinksFunction = () => [
  { rel: 'manifest', href: '/manifest.webmanifest' },
];

// Registers the PWA service worker generated by vite-plugin-pwa. Dynamically
// imported inside a client-only effect: `virtual:pwa-register` touches
// `navigator.serviceWorker`, which doesn't exist in the SSR/server bundle
// React Router builds even with ssr:false (see `build/server`, removed by the
// build script). In dev (devOptions off, the default here) registerSW is a
// safe no-op since no service worker file is served.
function useRegisterServiceWorker() {
  useEffect(() => {
    import('virtual:pwa-register').then(({ registerSW }) => {
      registerSW({ immediate: true });
    });
  }, []);
}

export function Layout({ children }: { children: React.ReactNode }) {
  useRegisterServiceWorker();

  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#F5F0E8" />
        <Meta />
        <Links />
      </head>
      <body>
        {children}
        <ScrollRestoration />
        <Scripts />
      </body>
    </html>
  );
}

export default function App() {
  // Starts observing Firebase identity for the lifetime of the app. No UI is
  // gated on it yet — the sign-in screen and the route guard are #9, the lock
  // screen is #10. This only makes the session store live, so those issues wire
  // up rather than bootstrap. With the Firebase env unset (CI, a fresh clone)
  // the store lands in 'unavailable' and the app still renders.
  useSessionBootstrap();

  return <Outlet />;
}

export function ErrorBoundary({ error }: Route.ErrorBoundaryProps) {
  let message = 'Oops!';
  let details = 'An unexpected error occurred.';
  let stack: string | undefined;

  if (isRouteErrorResponse(error)) {
    message = error.status === 404 ? '404' : 'Error';
    details =
      error.status === 404
        ? 'The requested page could not be found.'
        : error.statusText || details;
  } else if (import.meta.env.DEV && error && error instanceof Error) {
    details = error.message;
    stack = error.stack;
  }

  return (
    <main className="mx-auto max-w-page px-8 py-16">
      <h1 className="font-display text-stat text-text-primary">{message}</h1>
      <p className="mt-6 font-body text-body text-text-secondary">{details}</p>
      {stack && (
        <pre className="mt-8 w-full overflow-x-auto rounded-card bg-surface-inset p-6 font-mono text-row-sub text-text-secondary">
          <code>{stack}</code>
        </pre>
      )}
    </main>
  );
}
