import { useEffect } from 'react';
import {
  isRouteErrorResponse,
  Links,
  Meta,
  Outlet,
  Scripts,
  ScrollRestoration,
} from 'react-router';

import type { Route } from './+types/root';
import { DEFAULT_LOCALE } from './i18n';
import { useDocumentLocale } from './stores/use-locale';
import { useSessionBootstrap } from './stores/use-session';
import './app.css';

export const links: Route.LinksFunction = () => [
  { rel: 'manifest', href: '/manifest.webmanifest' },
];

// Registers the PWA service worker generated by vite-plugin-pwa. Dynamically
// imported inside a client-only effect: `virtual:pwa-register` touches
// `navigator.serviceWorker`, which doesn't exist in the SSR/server bundle
// React Router builds even with ssr:false (see `build/server`, removed by the
// build script). In dev (devOptions off, the default here) registerSW is a
// safe no-op since no service worker file is served.
function useRegisterServiceWorker() {
  useEffect(() => {
    import('virtual:pwa-register').then(({ registerSW }) => {
      registerSW({ immediate: true });
    });
  }, []);
}

// Publishes the db-layer test seam — development and emulator builds only.
//
// `app/db/db-test-handle.ts` carries the reasoning; the short version is that
// nothing in the app imports `app/db` or `app/crypto` yet (#9, #10), so the
// encrypted database layer had never executed in a browser and the
// `Dexie.waitFor` guarantee in the middleware was proven only against
// `fake-indexeddb`. `test/e2e/db-liveness.spec.ts` drives the real middleware
// through this handle.
//
// Three properties of this shape, all deliberate:
//
//   1. The mode comparison is written out in full rather than pulled from a
//      constant, so Vite's build-time substitution of `import.meta.env.MODE`
//      folds it to `false` in a production build and the whole statement goes.
//      `vite.config.ts` asserts the deletion by reading the emitted bundle
//      back. This mirrors `app/stores/session-instance.ts` exactly.
//   2. The import is **dynamic**, so production does not merely drop an
//      assignment — it never pulls `app/db` (and with it Dexie and hash-wasm)
//      into the module graph at all. A static import would ship the whole db
//      layer to real users for the sake of a branch that can never run.
//   3. Module scope with a `document` check rather than an effect, for one
//      measurable reason: an effect leaves `useEffect(() => {}, [])` behind in
//      production once the branch inside it folds away, and the production
//      bundle should be byte-for-byte what it would have been without this
//      seam. It is — verified by building both ways. The `document` check is
//      what `useRegisterServiceWorker` gets from being an effect: React Router
//      still emits a server bundle for the SPA prerender, and Dexie has no
//      business being evaluated there.
if (
  (import.meta.env.MODE === 'development' ||
    import.meta.env.MODE === 'emulator') &&
  typeof document !== 'undefined'
) {
  void import('./db/db-test-api').then(({ installDbTestHandle }) => {
    installDbTestHandle();
  });
}

export function Layout({ children }: { children: React.ReactNode }) {
  useRegisterServiceWorker();
  // FOUN-07: `<html lang>` must name the language the page is actually in, or
  // a screen reader pronounces Italian copy with English phonetics. See the
  // hook for why the attribute is written imperatively rather than rendered.
  useDocumentLocale();

  return (
    // The prerendered value, and only that. `ssr: false` means this file is
    // rendered to HTML once at build time, in Node, and every visitor is
    // served the same bytes — so this attribute cannot carry a detected
    // locale, and rendering one here would only be a hydration mismatch.
    // `useDocumentLocale` corrects the live document; this keeps the static
    // shell honest about what it is (English, and wordless).
    <html lang={DEFAULT_LOCALE}>
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#F5F0E8" />
        <Meta />
        <Links />
      </head>
      <body>
        {children}
        <ScrollRestoration />
        <Scripts />
      </body>
    </html>
  );
}

export default function App() {
  // Starts observing Firebase identity for the lifetime of the app. No UI is
  // gated on it yet — the sign-in screen and the route guard are #9, the lock
  // screen is #10. This only makes the session store live, so those issues wire
  // up rather than bootstrap. With the Firebase env unset (CI, a fresh clone)
  // the store lands in 'unavailable' and the app still renders.
  useSessionBootstrap();

  return <Outlet />;
}

export function ErrorBoundary({ error }: Route.ErrorBoundaryProps) {
  let message = 'Oops!';
  let details = 'An unexpected error occurred.';
  let stack: string | undefined;

  if (isRouteErrorResponse(error)) {
    message = error.status === 404 ? '404' : 'Error';
    details =
      error.status === 404
        ? 'The requested page could not be found.'
        : error.statusText || details;
  } else if (import.meta.env.DEV && error && error instanceof Error) {
    details = error.message;
    stack = error.stack;
  }

  return (
    <main className="mx-auto max-w-page px-8 py-16">
      <h1 className="font-display text-stat text-text-primary">{message}</h1>
      <p className="mt-6 font-body text-body text-text-secondary">{details}</p>
      {stack && (
        <pre className="mt-8 w-full overflow-x-auto rounded-card bg-surface-inset p-6 font-mono text-row-sub text-text-secondary">
          <code>{stack}</code>
        </pre>
      )}
    </main>
  );
}
